### ISSUE TITLE
To-Do routing and controlling

### ISSUE THREAD

**Issue by asynchroza** [asynchroza/notes-mailer#1]
- [ ] Create To-Do note - POST request
- [ ] Get To-Do note (should be retrieved by date) - GET request
- [ ] Delete To-Do note (past notes should be deleted) - DELETE request
- [ ] Edit To-Do note - PATCH request
